# https://docs.microsoft.com/en-us/azure/devops/artifacts/quickstarts/github-actions?view=azure-devops
name: Publish NuGet package

on:
  release:
    types: [published]

env:
  ARTIFACTS_FEED_URL: https://api.nuget.org/v3/index.json
  
jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Determine version for NuGet package
        run: echo NUGET_VERSION=${GITHUB_REF#refs/tags/v} >> $GITHUB_ENV
      
      - name: Replace version number in nuspec files
        run: 'sed -i -e "s/{{NuGetVersion}}/$NUGET_VERSION/g" *.nuspec'

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.2.0
          
      - name: Create main package
        run: nuget pack Neolution.CodeAnalysis.nuspec
          
      - name: Create TestsRuleset package
        run: nuget pack Neolution.CodeAnalysis.TestsRuleset.nuspec
          
      - name: Push all packages to Nuget.org
        run: dotnet nuget push --skip-duplicate -s $ARTIFACTS_FEED_URL -k $NUGET_AUTH_TOKEN **/*.nupkg
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY_NEOLUTION }}
        
  notify:
    needs: [pack-and-publish]
    runs-on: ubuntu-latest
    steps:
      - uses: neolution-ch/action-release-notifier@v1
        with:
          slack-token: ${{ secrets.SLACK_RELEASE_NOTIFIER_TOKEN }}
          slack-channel-ids: "C05DR8P010A"
