name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: "Type of release to create"
        default: stable
        options:
          - stable
          - alpha
          - beta
          - rc
          
      version_bump:
        type: choice
        description: "Which part of the version to increment"
        default: patch
        options:
          - patch
          - minor
          - major
          
      continue_prerelease:
        type: boolean
        description: "Continue an existing alpha/beta/rc series instead of starting a new one"
        default: false
        
      is_dry_run:
        type: boolean
        description: "Simulate the release without making any changes"
        default: false

jobs:
  release-it:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private_key: ${{ secrets.RELEASE_BOT_APP_PRIVATE_KEY }}

      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: initialize mandatory git config
        run: |
          git config user.name "GitHub Release Bot"
          git config user.email release-bot@neolution.ch

      - name: install release-it with plugins
        run: npm install -g release-it @release-it/keep-a-changelog

      - name: run release-it
        run: |
          params=()

          # Determine prerelease logic
          if [[ "${{ github.event.inputs.release_type }}" == "stable" ]]; then
            params+=(--${{ github.event.inputs.version_bump }})
          elif [[ "${{ github.event.inputs.continue_prerelease }}" == "true" ]]; then
            params+=(--increment=prerelease)
            params+=(--preRelease=${{ github.event.inputs.release_type }})
            params+=(--plugins.@release-it/keep-a-changelog.keepUnreleased)
            params+=(--no-plugins.@release-it/keep-a-changelog.strictLatest)
          else
            params+=(--${{ github.event.inputs.version_bump }})
            params+=(--preRelease=${{ github.event.inputs.release_type }})
            params+=(--plugins.@release-it/keep-a-changelog.keepUnreleased)
            params+=(--no-plugins.@release-it/keep-a-changelog.strictLatest)
          fi

          if [[ "${{ github.event.inputs.is_dry_run }}" == "true" ]]; then
            params+=(--dry-run)
          fi

          params+=(--ci)

          echo "command: release-it ${params[@]}"
          release-it "${params[@]}"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}