name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
   
jobs:
  publish:
    name: build & pack
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Needed for GitVersion to function correctly
                   
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        
      - name: Replace version number
        run: 'sed -i -e "s/{{NuGetVersion}}/$GITVERSION_NUGETVERSION/g" *.nuspec **/*.targets'

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
          
      - name: Pack main package
        run: nuget pack Neolution.CodeAnalysis.nuspec
          
      - name: Pack TestsRuleset package
        run: nuget pack Neolution.CodeAnalysis.TestsRuleset.nuspec
          
